server:
  port: 9900
  servlet:
    context-path: /
spring:
  application:
    name: demo-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  jmx:
    default-domain: jarboot-service
  jms:
    pub-sub-domain: true