server:
  port: ${port:9899}
  servlet:
    context-path: /
spring:
  application:
    name: jarboot-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  web:
    resources:
      static-locations: file:${jarboot.home}/static
  jmx:
    default-domain: jarboot-service
  jms:
    pub-sub-domain: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB
      max-request-size: 512MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: ${jarboot.db.driverClassName:org.apache.derby.jdbc.EmbeddedDriver}
    url: ${jarboot.db.url:jdbc:derby:${user.home}/jarboot/data/derby_data;create=true}
    data-username: ${jarboot.db.user:root}
    data-password: ${jarboot.db.password:root}
    hikari:
      minimum-idle: 2
      pool-name: jarboot_db_pool
logging:
  file:
    path: ${user.home}/jarboot/logs