server:
  port: 9899
  servlet:
    context-path: /
spring:
  application:
    name: jarboot-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  web:
    resources:
      static-locations: file:${JARBOOT_HOME}/static
  jmx:
    default-domain: jarboot-service
  jms:
    pub-sub-domain: true
logging:
  file:
    path: ${user.home}/jarboot/logs